### ISSUE TITLE
Red Iron Compound overflows microscope GUI into player inventory

### ISSUE THREAD

**Issue by nickpauwels1988** [AdlyTempleton/MineChem#194]
When you place a Red Iron Compound from Project Red into the microscope GUI while the microscope is in Chemical Decomposer mode, multiple compounds are placed into the player inventory, in this case iron and copper.

**Comment by jakimfett** [comment]
I believe this was fixed in v5.0.5-Dev5, what version are you running?

**Comment by nickpauwels1988** [comment]
v5.0.5-Dev5, not fixed.
http://gyazo.com/d5ae074b78177fdf1bca7beec88a17a4

**Comment by jakimfett** [comment]
I've coded a fix for this, it'll show up in the next dev release.
![](http://pics.jakimfett.com/2014-06-01_22-55-00.png)
The GUI still freaks out when an item like this is placed in it, but it won't spill over into the player's inventory anymore.
